[package]
name = "yucon-0_3"
version = "0.1.0"
authors = ["Blaine Murphy <agentkmurphy@gmail.com>"]
description = "General purpose unit conversion program"

[dependencies]
structopt = "0.2.14"
rustyline = "3.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
log = "0.4"
log4rs = "0.8"